// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5TWrTfbQ90VyXLAAciLgJHJx_Q0VymNE',
    appId: '1:741192779605:web:4b27c2a2528a34539751dc',
    messagingSenderId: '741192779605',
    projectId: 'booking-system-efa25',
    authDomain: 'booking-system-efa25.firebaseapp.com',
    storageBucket: 'booking-system-efa25.firebasestorage.app',
    measurementId: 'G-HBL9E2YFLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAUVQ_4jwmQT-MDs4x6YGtMD0gUhdjwEk',
    appId: '1:741192779605:android:5a78cad7874314c99751dc',
    messagingSenderId: '741192779605',
    projectId: 'booking-system-efa25',
    storageBucket: 'booking-system-efa25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNHF0-bBFK1yzqo2IBcwz9KOoCb6bPPTU',
    appId: '1:741192779605:ios:98d02de3c41d4e1f9751dc',
    messagingSenderId: '741192779605',
    projectId: 'booking-system-efa25',
    storageBucket: 'booking-system-efa25.firebasestorage.app',
    iosBundleId: 'com.example.flutterBookingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNHF0-bBFK1yzqo2IBcwz9KOoCb6bPPTU',
    appId: '1:741192779605:ios:98d02de3c41d4e1f9751dc',
    messagingSenderId: '741192779605',
    projectId: 'booking-system-efa25',
    storageBucket: 'booking-system-efa25.firebasestorage.app',
    iosBundleId: 'com.example.flutterBookingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5TWrTfbQ90VyXLAAciLgJHJx_Q0VymNE',
    appId: '1:741192779605:web:484a83c4d0842dc49751dc',
    messagingSenderId: '741192779605',
    projectId: 'booking-system-efa25',
    authDomain: 'booking-system-efa25.firebaseapp.com',
    storageBucket: 'booking-system-efa25.firebasestorage.app',
    measurementId: 'G-VFJ88WB7HT',
  );

}